describe('ADCShow', function () {

    var common,
        adcShow,
        spies = {},
        errMsg,
        successMsg;

    beforeEach(function () {
        // Clean the cache, obtain a fresh instance of the adcShow each time
        var adcShowKey   = require.resolve('../../app/show/ADCShow.js'),
            commonKey       = require.resolve('../../app/common/common.js');

        delete require.cache[commonKey];
        common = require('../../app/common/common.js');

        delete require.cache[adcShowKey];
        adcShow = require('../../app/show/ADCShow.js');

        // Messages
        errMsg      = common.messages.error;
        successMsg  = common.messages.success;

        // Court-circuit the validation outputs
        spies.writeError   = spyOn(common, 'writeError');
        spies.writeSuccess = spyOn(common, 'writeSuccess');
        spies.writeMessage = spyOn(common, 'writeMessage');
        spies.dirExists    = spyOn(common, 'dirExists');


    });


    function runSync(fn) {
        var wasCalled = false;
        runs( function () {
            fn(function () {
                wasCalled = true;
            });
        });
        waitsFor(function () {
            return wasCalled;
        });
    }


    describe('#show', function () {
        it("should output an error when the `output` option is not defined", function () {
            adcShow.show({});
            expect(common.writeError).toHaveBeenCalledWith(errMsg.noOutputDefinedForShow);
        });

        it("should output an error when the `fixture` option is not defined", function () {
            adcShow.show({
                output : 'Something'
            });
            expect(common.writeError).toHaveBeenCalledWith(errMsg.noFixtureDefinedForShow);
        });

        it("should call the program `ADXShell.exe` with the correct arguments", function () {
            var childProc = require('child_process'),
                spyExec   = spyOn(childProc, 'execFile');

            spyOn(process, 'cwd').andReturn('');

            spyExec.andCallFake(function (file, args) {
                expect(file).toBe('.\\ADXShell.exe');
                expect(args).toEqual(['show', '-output:something', '-fixture:single.xml', '/adc/path/dir']);
            });
            adcShow.show({
                output : 'something',
                fixture : 'single.xml'
            }, '/adc/path/dir');

            expect(childProc.execFile).toHaveBeenCalled();
        });

        it("should call the program `ADCShell.exe` with the `-masterPage` parameter when it's defined", function() {
            var childProc = require('child_process'),
                spyExec   = spyOn(childProc, 'execFile');

            spyOn(process, 'cwd').andReturn('');

            spyExec.andCallFake(function (file, args) {
                expect(file).toBe('.\\ADXShell.exe');
                expect(args).toEqual(['show', '-output:something', '-fixture:single.xml', '-masterPage:mp.html', '/adc/path/dir']);
            });
            adcShow.show({
                output : 'something',
                fixture : 'single.xml',
                masterPage : 'mp.html'
            }, '/adc/path/dir');

            expect(childProc.execFile).toHaveBeenCalled();
        });

        it("should call the `callback` function with error when an error occurred", function () {
            runSync(function (done) {
                adcShow.show({}, null, function(err, output) {
                    expect(err instanceof  Error).toBe(true);
                    expect(err.message).toEqual(errMsg.noOutputDefinedForShow);
                    done();
                });
            });
        });

        it("should call the `callback` function with the output generated by the `ADXShell.exe` process", function () {

            var childProc = require('child_process'),
                spyExec   = spyOn(childProc, 'execFile');

            spyOn(process, 'cwd').andReturn('');

            spyExec.andCallFake(function (file, args, options, cb) {
                cb(null, 'TEST OUTPUT', null);
            });


            runSync(function (done) {
                adcShow.show({
                    output : 'something',
                    fixture : 'single.xml'
                }, '/adc/path/dir', function (err, output) {
                    expect(output).toEqual('TEST OUTPUT');
                    done();
                });
            });
        });
    });
});

